use_frameworks!

target 'DemoFramework_Example' do
  pod 'DemoFramework', :path => '../'

  target 'DemoFramework_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
